implemented interactive shell for the manage function

diff --git a/build_functions b/build_functions
--- a/build_functions
+++ b/build_functions
@@ -39,12 +39,14 @@ ${bold}Usage: ${0} [General options] [Sub options] name
 
 e.g obarun-build Create create container
     obarun-build C c container
-    obarun-build B b cups${reset}
+    obarun-build B b cups
+    obarun-build M container
+    obarun-build M network${reset}
     
 ${bold}General options :${reset}
     C, Create : create a container
     B, Build : build a package onto a container
-    M, Manage : manage a container
+    M, Manage : open an interactive shell to manage a named container
 
 ${bold}Sub options :${reset}
     for Create :
@@ -53,19 +55,14 @@ ${bold}Sub options :${reset}
         b, build : build a package onto a container
         r, remake : build a package onto an archived container
     for Manage :
-        all lxc- command. Can be designed by the first letter
-        but some parsing are impossible. The script will warm you.
-        e.g obarun-build M info container
-            obarun-build M i container
-        You enter extra options from lxc
-           e.g obarun-build start container --logfile out
-           e.g obarun-build start container --help 
+        n, network : manage the bridge
 EOF
 	exit 0
 }
 
 # ${1} command to pass
 # ${2} arguments to pass. Can be empty
+# functions return 0 on success, 1 on other case
 lxc_command_parse(){
 	local command loop_ ret
 	local -a parse_opt rest_opt
@@ -75,30 +72,25 @@ lxc_command_parse(){
 
 	
 	# check if lxc-${command} exist
-	for loop_ in $(ls /bin/|grep lxc-|sed 's:*::'); do
-		if [[ lxc-"${command}" == "${loop_}" ]]; then
-			ret=0
-			break
-		else
-			ret=1
-		fi
-	done
-	
-	if (( ! $ret )); then
+	check_lxc_command "${command}"
+
+	if (( ! $? )); then
 		if [[ "${command}" == @(ls|autostart|checkconfig|top|usernsexec) ]]; then
 			rest_opt=( "${parse_opt[@]:1}" )
-			"lxc-${command}" "${rest_opt[@]}" || die " Aborting command : lxc-${command} ${parse_opt[@]:1}"
+			"lxc-${command}" "${rest_opt[@]}" || return 1 #die " Aborting command : lxc-${command} ${parse_opt[@]:1}"
 		else
 			if [[ -z "${parse_opt[1]}" ]]; then
-				die " name must not be empty"
+				echo_error " name must not be empty"
+				return 1
 			fi
 			# if the container was not stopped before exiting of it
 			# the command stop may take time, just warm them
 			if [[ "${command}" == "stop" ]]; then
-					echo_notvalid " Trying to shutdown ${named}, this may take time..."
+				echo_notvalid " Trying to shutdown ${named}, this may take time..."
 			fi
 			rest_opt=( "${parse_opt[@]:2}" )
-			"lxc-${command}" -n "${parse_opt[1]}" "${rest_opt[@]}" || die " Aborting command : lxc-${command} -n ${parse_opt[1]} ${rest_opt[@]}"
+			echo "lxc-${command}" -n "${parse_opt[1]}" "${rest_opt[@]}"
+			"lxc-${command}" -n "${parse_opt[1]}" "${rest_opt[@]}" || return 1 #die " Aborting command : lxc-${command} -n ${parse_opt[1]} ${rest_opt[@]}"
 		fi
 	else
 		die " lxc-${command} doesn't exist"
@@ -201,8 +193,8 @@ build(){
 	# copy $sources/$named files onto the container
 	#mkdir -p "${target}/${named}-${named_version}/${workdir}/rootfs/tmp/${named}-${named_version}" || die " Impossible to create ${target}/${named}/${workdir}/rootfs/tmp/${named}-${named_version}"
 	cp -ra "${sources}/${named}" "${target}/${named}-${named_version}/${workdir}/rootfs/tmp/${named}-${named_version}" || die " Impossible to copy file from ${sources}/${named}-${named_version}"
-	#mv "${target}/${named}-${named_version}/${workdir}/rootfs/tmp/${named}" "${target}/${named}-${named_version}/${workdir}/rootfs/tmp/${named}-${named_version}"
-	#exit
+
+
 	# remove existing package and src, pkg directories
 	rm -f "${target}/${named}-${named_version}/${workdir}/rootfs/tmp/${named}"/*.pkg.* &>/dev/null
 	rm -rf "${target}/${named}-${named_version}/${workdir}/rootfs/tmp/${named}"/{src,pkg} &>/dev/null
@@ -225,12 +217,17 @@ build(){
 	cp -f "${target}/${named}-${named_version}/${workdir}/rootfs/tmp/${named}-${named_version}"/*.pkg.tar.* "${result_pkg}/${named}/${named_version}" || echo_info " WARNING : the resulting package can be copied to ${result_pkg}/${named}/${named_version}"
 	
 	# stop the container
-	lxc_command_parse "stop" "${named}-${named_version}" -k
-
+	lxc_command_parse "stop" "${named}-${named_version}" -k || die " Impossible to stop the container"
+	
+	echo_display " Would you like to destroy the container? [y|n]"
+	reply_answer
+	if (( ! $? )); then
+		lxc_command_parse "destroy" "${named}-${named_version}"
+	fi
 }
 
 remake(){
-	echo_bold " Features not implemented yet"
+	echo_bold " Features not implemented"
 }
 
 ################################################################################################################
@@ -239,3 +236,256 @@ remake(){
 ##																											  ##
 ################################################################################################################
 
+# ${1} command to check
+check_lxc_command(){
+	local loop_ command ret
+	command="${1}"
+
+	for loop_ in $(ls /bin/|grep lxc-|sed 's:*::'); do
+		if [[ lxc-"${command}" == "${loop_}" ]]; then
+			ret=0
+			break
+		else
+			ret=1
+		fi
+	done
+	# ret=1 else return 1
+	if [[ "${ret}" == 1 ]]; then
+		return 1
+	else
+		return 0
+	fi
+	
+	unset ret loop_ command
+}
+
+# ${1} name of the container to manage.
+# ${2} come from switch or not : 0 for not
+# this is avoid to display the first menu
+manage(){
+	local ans ans_command ans_full parse_ans named _sw sw empty_named pick container_exist ret
+	local -a container_list
+	named="${1}"
+	container_list=( $(lxc-ls -1) )
+	
+	
+	check_existing_container(){
+			select pick in "${container_list[@]}"; do
+				case "$pick" in
+					*)if check_elements "$pick" "${container_list[@]}"; then
+						named="${pick}"
+						break
+					else 
+						echo_retry " Invalid number, retry :"
+					fi
+				esac
+			done
+	}
+	
+	if [[ -z "${named}" ]]; then
+		echo_info " name must not be empty"
+		echo_info " please pick one on the following list"
+		
+		check_existing_container
+	else
+		for container_exist in "${container_list[@]}"; do
+			if [[ "${named}" == "${container_exist}" ]]; then
+				ret=0
+				break
+			else
+				ret=1
+			fi
+		done
+		if (( $ret )); then
+			echo_info " ${named} doesn't exist"
+			echo_info " please pick one on the following list"
+			check_existing_container
+		fi
+		unset ret
+	fi
+	
+	_sw="${2}"
+	
+	# display or not the following line
+	if [[ "${_sw}" == 0 ]] || [[ -z "${_sw}" ]]; then
+		printf "\n" >&1
+		printf " Type help to see option\n" >&1
+		printf " Type quit for exit\n" >&1
+	fi
+	
+	while true; do
+		echo ""
+		
+		read -p "Manage ${named} > " ans 
+		
+		parse_ans=( ${ans[@]} )
+		ans_command=( ${parse_ans[0]} )
+		ans_full=( ${parse_ans[@]:1} )
+		
+		check_var(){
+			echo ans="${ans[@]}"
+			echo parse_ans="${parse_ans[@]}"
+			echo ans_command="${ans_command}"
+			echo ans_full="${ans_full[@]}"
+		}
+		#check_var
+		
+		case "${ans_command}" in
+			network)
+				manage_network
+				;;
+			switch)
+				named="${parse_ans[1]}"
+				sw=1
+				break
+				;;
+			help)
+				manage_help
+				;;
+			quit) 
+				exit
+				;;
+			*)
+				# check if lxc-${command} exist
+				check_lxc_command "${ans_command}"
+							
+				if (( $? )); then
+					printf " Incorrect command, try help\n" >&1
+				else
+					if [[ "${ans_command}" == @(ls|autostart|checkconfig|top|usernsexec) ]]; then
+						# eval here can be dangerous, need to find a turn around
+						eval lxc-"${ans_command}" "${ans_full[@]}"
+						(( ! $? )) || echo_info "Warning : the command failed, see above"
+					else
+						# eval here can be dangerous, need to find a turn around
+						eval lxc-"${ans_command}" -n "${named}" "${ans_full[@]}"
+						# don't stop the script if the command fail, but warm it
+						(( ! $? )) || echo_info "Warning : the command failed, see above"
+					fi
+				fi
+		esac
+	done
+	if (( $sw )); then
+		manage "${named}" "1"
+	fi
+}
+
+manage_help(){
+	
+	printf "%-15s %-15s\n" "attach" "start a process inside a running container" >&1
+	printf "%-15s %-15s\n" "autostart" "start/stop/kill auto-started containers" >&1
+	printf "%-15s %-15s\n" "cgroup" "start a process inside a running container" >&1
+	printf "%-15s %-15s\n" "checkconfig" "start a process inside a running container" >&1
+	printf "%-15s %-15s\n" "checkpoint" "checkpoint a container" >&1
+	printf "%-15s %-15s\n" "config" "query LXC system configuration" >&1
+	printf "%-15s %-15s\n" "console" "launch a console for the specified container" >&1
+	printf "%-15s %-15s\n" "copy" "copy an existing container" >&1
+	printf "%-15s %-15s\n" "create" "creates a container" >&1
+	printf "%-15s %-15s\n" "destroy" "destroy a container" >&1
+	printf "%-15s %-15s\n" "device" "manage devices of running containers" >&1
+	printf "%-15s %-15s\n" "execute" "run an application inside a container" >&1
+	printf "%-15s %-15s\n" "freeze" "freeze all the container's processes" >&1
+	printf "%-15s %-15s\n" "info" "query information about a container" >&1
+	printf "%-15s %-15s\n" "ls" "list the containers existing on the system" >&1
+	printf "%-15s %-15s\n" "monitor" "monitor the container state" >&1
+	printf "%-15s %-15s\n" "network" "create/start/stop/destroy the bridge" >&1
+	printf "%-15s %-15s\n" "quit" "exit from this menu" >&1
+	printf "%-15s %-15s\n" "snapshot" "snapshot an existing container" >&1
+	printf "%-15s %-15s\n" "start" "start a container" >&1
+	printf "%-15s %-15s\n" "stop" "stop a container" >&1
+	printf "%-15s %-15s\n" "switch" "manage the named container" >&1
+	printf "%-15s %-15s\n" "top" "monitor container statistics" >&1
+	printf "%-15s %-15s\n" "unfreeze" "thaw all the container's processes" >&1
+	printf "%-15s %-15s\n" "unshare" "run a task in a new set of namespaces" >&1
+	printf "%-15s %-15s\n" "usernsexec" "run a task as root in a new user namespace" >&1
+	printf "%-15s %-15s\n" "wait" "wait for a specific container state" >&1
+	printf "%-15s %-15s\n" "" >&1
+	printf "%-15s %-15s\n" "" >&1
+	printf "%-15s %-15s\n" "If you want more information about a command,"
+	printf "%-15s %-15s\n" "type e.g start --help"
+	
+}
+
+manage_network(){
+	local ans
+	
+	printf "\n" >&1
+	printf " Type help to see option to control the bridge\n" >&1
+	printf " Type quit for exit\n" >&1
+	printf "\n" >&1
+	
+	while true; do
+		read -e -p "Manage network > " ans
+		case "${ans}" in
+			create)
+				network_create
+				;;
+			start)
+				network_start
+				;;
+			stop)
+				network_stop
+				;;
+			destroy)
+				network_destroy
+				;;
+			show)
+				network_show
+				;;
+			help)
+				manage_network_help
+				;;
+			quit)
+				break
+				;;
+			*)
+				printf " Incorrect command, try help\n" >&1
+				;;
+		esac
+	done
+}
+
+manage_network_help(){
+	printf "%-15s %-15s\n" "create" "create the bridge and start it" >&1
+	printf "%-15s %-15s\n" "destroy" "destroy the bridge" >&1
+	printf "%-15s %-15s\n" "start" "active the bridge" >&1
+	printf "%-15s %-15s\n" "stop" "disactive the bridge" >&1
+	printf "%-15s %-15s\n" "show" "show network" >&1
+}
+
+network_destroy(){
+	ip link set "${host_interface}" nomaster
+	ip link set "${bridge_interface}" down
+	ip link delete "${bridge_interface}" type bridge
+	ip route add default via "${router_addr}"
+}
+
+network_create(){
+	
+	# check if the bridge exist
+	# if not, create it
+	ip link show type bridge | grep ${bridge_interface} &>/dev/null
+	if (( $? )); then
+		ip link add name "${bridge_interface}" address 00:16:3e:$(openssl rand -hex 3| sed 's/\(..\)/\1:/g; s/.$//') type bridge
+		ip link set "${bridge_interface}" up
+		ip addr add "${bridge_addr}" dev "${bridge_interface}" 
+		ip link set "${host_interface}" master "${bridge_interface}" 
+	fi
+	if ! $(grep -q "POSTROUTING -o ${host_interface} -j" /etc/iptables/iptables.rules 2>/dev/null); then
+	
+		iptables -t nat -A POSTROUTING -o "${host_interface}" -j MASQUERADE
+	
+		echo_info "-t nat -A POSTROUTING -o "${host_interface}" -j MASQUERADE" 
+		echo_info "was added to your /etc/iptables/iptables.rules"
+	fi
+}
+network_show(){
+	ip link show
+}
+network_start(){
+	ip link set "${host_interface}" master "${bridge_interface}"
+}
+
+network_stop(){
+	ip link set "${host_interface}" nomaster
+}
