put global variables with cap letter, fix minor bugs

diff --git a/build_functions b/build_functions
--- a/build_functions
+++ b/build_functions
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/bash
 #
 # Functions file for obarun-build package
 #
@@ -16,18 +16,21 @@
 # but WITHOUT ANY WARRANTY; without even the implied warranty of
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
  
-
-shopt -s extglob
-
-source /usr/lib/obarun/common_functions
-source /etc/obarun/build.conf
-
-templates="${templates:-/usr/share/obarun/obarun-build/templates}"
-workdir="container"
-workconf="config"
+TEMPLATES="${TEMPLATES:-/usr/share/obarun/obarun-build/templates}"
+WORKDIR="container"
+WORKCONF="config"
 
 clean_install(){
-	echo_bold "clean install"
+	
+	echo_display " Cleaning up"
+	
+	if [[ -d "${TARGET}/${named}/${WORKCONF}" ]]; then
+		echo_valid " Removing ${TARGET}/${named}/${WORKCONF}"
+		rm -rf "${TARGET}/${named}/"
+	fi
+	
+	echo_valid " Restore your shell options"
+	shellopts_restore
 	
 	exit
 }
@@ -92,11 +95,9 @@ lxc_command_parse(){
 			"lxc-${command}" -n "${parse_opt[1]}" "${rest_opt[@]}" || return 1 #die " Aborting command : lxc-${command} -n ${parse_opt[1]} ${rest_opt[@]}"
 		fi
 	else
-		die " lxc-${command} doesn't exist"
+		die " lxc-${command} doesn't exist" "clean_install"
 	fi
-	
-	#echo_valid " Done"
-	
+		
 	return 0
 }
 
@@ -106,7 +107,7 @@ create(){
 	local file named
 	local -a file_list _args
 	
-	mapfile -t file_list < <(ls --group-directories-first ${templates}/*)
+	mapfile -t file_list < <(ls --group-directories-first ${TEMPLATES}/*)
 	
 	named="${1}"
 	_args=( "${@}" )
@@ -114,7 +115,7 @@ create(){
 
 	# check if container directory exist
 	# if yes then exit container exit
-	check_dir "${target}/${named}"
+	check_dir "${TARGET}/${named}"
 	if (( ! $? )); then
 		echo_info " Container already exit, do you want overwrite it? [y|n] :"
 		reply_answer
@@ -122,31 +123,31 @@ create(){
 			die " Exiting"
 		fi
 	fi
-	# check if templates directory exist on $target
+	# check if templates directory exist on $TARGET
 	# create it if doesn't exist
-	check_dir "${target}/${named}/${workconf}"
+	check_dir "${TARGET}/${named}/${WORKCONF}"
 	if (( $? )); then
-		echo_display " Create ${target}/${named}/${workconf}"
-		mkdir -p "${target}/${named}/${workconf}" || die " Impossible to create directory ${target}/${named}/${workconf}" 
+		echo_display " Create ${TARGET}/${named}/${WORKCONF}"
+		mkdir -p "${TARGET}/${named}/${WORKCONF}" || die " Impossible to create directory ${TARGET}/${named}/${WORKCONF}" "clean_install"
 	fi
 	# check if configuration templates exist
 	# if not create it
 	for file in "${file_list[@]}"; do
 		file=${file##*/}
-		search_in_dir "${target}/${named}" "${workconf}" "${file}"
+		search_in_dir "${TARGET}/${named}" "${WORKCONF}" "${file}"
 		if (( $? )); then
-			echo_display " Copy ${file} templates file to ${target}/${named}/${workconf}"
-			cp "${templates}/${file}" "${target}/${named}/${workconf}" || die " Impossible to copy ${file}"
+			echo_display " Copy ${file} templates file to ${TARGET}/${named}/${WORKCONF}"
+			cp "${TEMPLATES}/${file}" "${TARGET}/${named}/${WORKCONF}" || die " Impossible to copy ${file}" "clean_install"
 		fi
 	done
 	
 	# now we have to correct place to find configuration file to create and configure the container
 	# so, exporting the good one
-	export create_conf="${target}/${named}/${workconf}/create.conf"
+	export create_conf="${TARGET}/${named}/${WORKCONF}/create.conf"
 	export named="${named}"
-	export workdir="${workdir}"
-	export workconf="${workconf}"
-	lxc_command_parse "create" "${named}" -t "${target}/${named}/${workconf}/create" "${_args[@]}" || die " Impossible to create the container"
+	export WORKDIR="${WORKDIR}"
+	export WORKCONF="${WORKCONF}"
+	lxc_command_parse "create" "${named}" -t "${TARGET}/${named}/${WORKCONF}/create" "${_args[@]}" || die " Impossible to create the container" "clean_install"
 	
 }
 
@@ -160,25 +161,31 @@ build(){
 	_args=( "${_args[@]:1}" )
 
 	# check if sources variables is set
-	if [[ -z "${sources}" ]]; then
-		die " Aborting : sources variables on /etc/obarun/build.conf is not set"
+	if [[ -z "${SOURCES}" ]]; then
+		die " Aborting : sources variables on /etc/obarun/build.conf is not set" "clean_install"
 	fi
 	
-	# be sure that $named exist on $sources directory
-	check_dir "${sources}/${named}"
+	# be sure that $named exist on $SOURCES directory
+	check_dir "${SOURCES}/${named}"
 	if (( $? )); then
-		die " ${named} do not exist on ${sources} directory"
+		die " ${named} do not exist on ${SOURCES} directory" "clean_install"
 	fi
 	
-	# be sure that a PKGBUILD file exit on $sources/$named
-	search_in_dir "${sources}" "${named}" "PKGBUILD"
+	# be sure that a PKGBUILD file exit on $SOURCES/$named
+	search_in_dir "${SOURCES}" "${named}" "PKGBUILD"
 	if (( $? )); then
-		die " Aborting : a PKGBUILD file must at least exist into ${sources} directory"
+		die " Aborting : a PKGBUILD file must at least exist into ${SOURCES} directory" "clean_install"
 	fi
+	
 	# retrieve pkgver and pkgrel to implemente them onto the name
-	pkgver_=$(grep pkgver= "${sources}/${named}/PKGBUILD" | awk -F"=" '{print $2}')
-	pkgrel_=$(grep pkgrel= "${sources}/${named}/PKGBUILD" | awk -F"=" '{print $2}')
-	named_version="${pkgver_}-${pkgrel_}"
+	# sanitize the pkgver pkgrel first
+	unset pkgver pkgrel
+	
+	source "${SOURCES}/${named}/PKGBUILD"
+	
+	_pkgver="$pkgver"
+	_pkgrel="$pkgrel"
+	named_version="${_pkgver}-${_pkgrel}"
 	
 	# be sure that the named container doesn't exist
 	lxc-ls | grep "${named}-${named_version}" &>/dev/null
@@ -189,40 +196,39 @@ build(){
 	# create the container
 	create "${named}-${named_version}" "${_args[@]}"
 	
-	# copy $sources/$named files onto the container
-	#mkdir -p "${target}/${named}-${named_version}/${workdir}/rootfs/tmp/${named}-${named_version}" || die " Impossible to create ${target}/${named}/${workdir}/rootfs/tmp/${named}-${named_version}"
-	cp -ra "${sources}/${named}" "${target}/${named}-${named_version}/${workdir}/rootfs/tmp/${named}-${named_version}" || die " Impossible to copy file from ${sources}/${named}-${named_version}"
+	# copy $SOURCES/$named files onto the container
+	cp -ra "${SOURCES}/${named}" "${TARGET}/${named}-${named_version}/${WORKDIR}/rootfs/tmp/${named}-${named_version}" || die " Impossible to copy file from ${SOURCES}/${named}-${named_version}" "clean_install"
 
 
 	# remove existing package and src, pkg directories
-	rm -f "${target}/${named}-${named_version}/${workdir}/rootfs/tmp/${named}"/*.pkg.* &>/dev/null
-	rm -rf "${target}/${named}-${named_version}/${workdir}/rootfs/tmp/${named}"/{src,pkg} &>/dev/null
+	rm -f "${TARGET}/${named}-${named_version}/${WORKDIR}/rootfs/tmp/${named}"/*.pkg.* &>/dev/null
+	rm -rf "${TARGET}/${named}-${named_version}/${WORKDIR}/rootfs/tmp/${named}"/{src,pkg} &>/dev/null
 	
 	# start the container
-	lxc_command_parse "start" "${named}-${named_version}" || die " Aborting : impossible to start the container ${named}-${named_version}"
+	lxc_command_parse "start" "${named}-${named_version}" || die " Aborting : impossible to start the container ${named}-${named_version}" "clean_install"
 	
 	# give a good permissions at the tmp/$named onto the container
-	lxc_command_parse "attach" "${named}-${named_version}" --clear-env -v named="${named}-${named_version}" -v newuser="${newuser}" -- bash -c 'echo "${newuser}" "ALL=(ALL)" NOPASSWD: ALL >> /etc/sudoers'
-	lxc_command_parse "attach" "${named}-${named_version}" --clear-env -v named="${named}-${named_version}" -v newuser="${newuser}" -- bash -c 'chown -R "${newuser}":users /tmp/"${named}"'
+	lxc_command_parse "attach" "${named}-${named_version}" --clear-env -v named="${named}-${named_version}" -v newuser="${NEWUSER}" -- bash -c 'echo "${newuser}" "ALL=(ALL)" NOPASSWD: ALL >> /etc/sudoers'
+	lxc_command_parse "attach" "${named}-${named_version}" --clear-env -v named="${named}-${named_version}" -v newuser="${NEWUSER}" -- bash -c 'chown -R "${newuser}":users /tmp/"${named}"'
 	
 	# build the package
-	lxc_command_parse "attach" "${named}-${named_version}" --clear-env -v named="${named}-${named_version}" -v newuser="${newuser}" -- bash -c 'cd /tmp/"${named}"; su "${newuser}"  -c "updpkgsums; makepkg -Cs --noconfirm"'
+	lxc_command_parse "attach" "${named}-${named_version}" --clear-env -v named="${named}-${named_version}" -v newuser="${NEWUSER}" -- bash -c 'cd /tmp/"${named}"; su "${newuser}"  -c "updpkgsums; makepkg -Cs --noconfirm"'
 	
 	# copy the resulting package on the right place
-	check_dir "${result_pkg}/${named}/${named_version}"
+	check_dir "${SAVE_PKG}/${named}/${named_version}"
 	if (( $? )); then
-		mkdir -p "${result_pkg}/${named}/${named_version}"
+		mkdir -p "${SAVE_PKG}/${named}/${named_version}"
 	fi
-	cp -f "${target}/${named}-${named_version}/${workdir}/rootfs/tmp/${named}-${named_version}"/*.pkg.tar.* "${result_pkg}/${named}/${named_version}" || echo_info " WARNING : the resulting package can be copied to ${result_pkg}/${named}/${named_version}"
+	cp -f "${TARGET}/${named}-${named_version}/${WORKDIR}/rootfs/tmp/${named}-${named_version}"/*.pkg.tar.* "${SAVE_PKG}/${named}/${named_version}" || echo_info " WARNING : the resulting package can be copied to ${SAVE_PKG}/${named}/${named_version}"
 	
 	# stop the container
-	lxc_command_parse "stop" "${named}-${named_version}" -k || die " Impossible to stop the container"
+	lxc_command_parse "stop" "${named}-${named_version}" -k || die " Impossible to stop the container" "clean_install"
 	
 	echo_display " Would you like to destroy the container? [y|n]"
 	reply_answer
 	if (( ! $? )); then
 		lxc_command_parse "destroy" "${named}-${named_version}"
-		rm -rf "${target}/${named}-${named_version}"
+		rm -rf "${TARGET}/${named}-${named_version}"
 	fi
 }
 
@@ -237,25 +243,19 @@ remake(){
 ################################################################################################################
 
 # ${1} command to check
+# return 0 on success,1 for fail
 check_lxc_command(){
 	local loop_ command ret
 	command="${1}"
 
 	for loop_ in $(ls /bin/|grep lxc-|sed 's:*::'); do
 		if [[ lxc-"${command}" == "${loop_}" ]]; then
-			ret=0
-			break
-		else
-			ret=1
+			return 0
 		fi
 	done
-	# ret=1 else return 1
-	if [[ "${ret}" == 1 ]]; then
-		return 1
-	else
-		return 0
-	fi
 	
+	return 1
+		
 	unset ret loop_ command
 }
 
@@ -454,28 +454,28 @@ manage_network_help(){
 }
 
 network_destroy(){
-	ip link set "${host_interface}" nomaster
-	ip link set "${bridge_interface}" down
-	ip link delete "${bridge_interface}" type bridge
-	ip route add default via "${router_addr}"
+	ip link set "${HOST_INTERFACE}" nomaster
+	ip link set "${BRIDGE_INTERFACE}" down
+	ip link delete "${BRIDGE_INTERFACE}" type bridge
+	ip route add default via "${ROUTER_ADDR}"
 }
 
 network_create(){
 	
 	# check if the bridge exist
 	# if not, create it
-	ip link show type bridge | grep ${bridge_interface} &>/dev/null
+	ip link show type bridge | grep ${BRIDGE_INTERFACE} &>/dev/null
 	if (( $? )); then
-		ip link add name "${bridge_interface}" address 00:16:3e:$(openssl rand -hex 3| sed 's/\(..\)/\1:/g; s/.$//') type bridge
-		ip link set "${bridge_interface}" up
-		ip addr add "${bridge_addr}" dev "${bridge_interface}" 
-		ip link set "${host_interface}" master "${bridge_interface}" 
+		ip link add name "${BRIDGE_INTERFACE}" address 00:16:3e:$(openssl rand -hex 3| sed 's/\(..\)/\1:/g; s/.$//') type bridge
+		ip link set "${BRIDGE_INTERFACE}" up
+		ip addr add "${BRIDGE_ADDR}" dev "${BRIDGE_INTERFACE}" 
+		ip link set "${HOST_INTERFACE}" master "${BRIDGE_INTERFACE}" 
 	fi
-	if ! $(grep -q "POSTROUTING -o ${host_interface} -j" /etc/iptables/iptables.rules 2>/dev/null); then
+	if ! $(grep -q "POSTROUTING -o ${HOST_INTERFACE} -j" /etc/iptables/iptables.rules 2>/dev/null); then
 	
-		iptables -t nat -A POSTROUTING -o "${host_interface}" -j MASQUERADE
+		iptables -t nat -A POSTROUTING -o "${HOST_INTERFACE}" -j MASQUERADE
 	
-		echo_info "-t nat -A POSTROUTING -o "${host_interface}" -j MASQUERADE" 
+		echo_info "-t nat -A POSTROUTING -o "${HOST_INTERFACE}" -j MASQUERADE" 
 		echo_info "was added to your /etc/iptables/iptables.rules"
 	fi
 }
@@ -483,9 +483,9 @@ network_show(){
 	ip link show
 }
 network_start(){
-	ip link set "${host_interface}" master "${bridge_interface}"
+	ip link set "${HOST_INTERFACE}" master "${BRIDGE_INTERFACE}"
 }
 
 network_stop(){
-	ip link set "${host_interface}" nomaster
+	ip link set "${HOST_INTERFACE}" nomaster
 }
diff --git a/templates/create b/templates/create
--- a/templates/create
+++ b/templates/create
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/bash
 #
 # template script for generating Obarun container with lxc
 #	
@@ -18,19 +18,44 @@
 
 # functions file for obarun-build package
 
+sourcing(){
+	
+	local list
+	
+	for list in /usr/lib/obarun/{common_functions,build_functions} /etc/obarun/build.conf; do
+		if [[ -f "${list}" ]]; then
+			source "${list}"
+		else
+			echo_error " Missing file : ${list}"
+			exit	
+		fi
+	done
+	
+	unset list
+}
+sourcing
 
-source /usr/lib/obarun/common_functions
-source /etc/obarun/build.conf
-source /usr/lib/obarun/build_functions
 source "${create_conf}"
+
+shellopts_save
+shellopts_set_unset "extglob" 0
 
 trap "clean_install"  TERM HUP QUIT INT ERR KILL STOP 
 
 clean_install() {
+    
     echo_display " Cleaning up"
+    
+    echo_valid " Destroying $named"
     lxc-destroy -n "${named}"
-    rm -rf "${cont_path}"
+    rm -rf "${CONT_PATH}"
+    
+    echo_valid " Destroying network"
     network_destroy
+    
+    echo_valid " Restore your shell options"
+    shellopts_restore
+    
     exit
 }
 
@@ -39,7 +64,6 @@ for arg in "$@"; do
     [ "$arg" = "--" ] && break
     if [ "$arg" = "--mapped-uid" -o "$arg" = "--mapped-gid" ]; then
         echo "This template can't be used for unprivileged containers." 1>&2
-        echo "You may want to try the \"download\" template instead." 1>&2
         exit 1
     fi
 done
@@ -50,46 +74,46 @@ export PATH=$PATH:/usr/local/bin:/usr/bin:/sbin:/bin
 # Ensure strict root's umask doesn't render the VM unusable
 umask 022
 
-if [ -z "$arch" ]; then
+if [ -z "$ARCH" ]; then
 	case "$(uname -m)" in
-		i?86) arch=i486 ;;
-		arm*) arch=arm ;;
-		*) arch=$(uname -m) ;;
+		i?86) ARCH=i486 ;;
+		arm*) ARCH=arm ;;
+		*) ARCH=$(uname -m) ;;
 	esac
 fi
 
 sanitize(){
-	if [ -d "${cont_path}" ]; then
-		rm -rf "${cont_path}"
+	if [ -d "${CONT_PATH}" ]; then
+		rm -rf "${CONT_PATH}"
 	fi
-	if [ -d _cont_conf ]; then
-		lxc-destroy -n "${named}"
-    fi
+	#if [ -d "${CONT_CONF}" ]; then
+	#	lxc-destroy -n "${named}"
+    #fi
 }
 
 create_dir(){
 	
-	echo_notvalid " Create needed directory in ${cont_rootfs}"
-	mkdir -m 0755 -p "${cont_rootfs}"/var/{cache/pacman/pkg,lib/pacman,lib/pacman/sync,log} "${cont_rootfs}"/{dev,run,etc,etc/pacman.d}
-	mkdir -m 0755 -p "${cont_rootfs}"/dev/{pts,shm}
-	mkdir -m 1777 -p "${cont_rootfs}"/tmp
-	mkdir -m 0555 -p "${cont_rootfs}"/{sys,proc}
+	echo_notvalid " Create needed directory in ${CONT_ROOTFS}"
+	mkdir -m 0755 -p "${CONT_ROOTFS}"/var/{cache/pacman/pkg,lib/pacman,lib/pacman/sync,log} "${CONT_ROOTFS}"/{dev,run,etc,etc/pacman.d}
+	mkdir -m 0755 -p "${CONT_ROOTFS}"/dev/{pts,shm}
+	mkdir -m 1777 -p "${CONT_ROOTFS}"/tmp
+	mkdir -m 0555 -p "${CONT_ROOTFS}"/{sys,proc}
 	
 	return 0
 }
 
 pac_file(){
 	
-	if [[ -d /etc/pacman.d/gnupg && ! -d $cont_rootfs/etc/pacman.d/gnupg ]]; then
+	if [[ -d /etc/pacman.d/gnupg && ! -d $CONT_ROOTFS/etc/pacman.d/gnupg ]]; then
 		echo_display " Copying gnupg directory"
-		cp -a /etc/pacman.d/gnupg "${cont_rootfs}/etc/pacman.d/" || die " Impossible to copy gnupg directory"
+		cp -a /etc/pacman.d/gnupg "${CONT_ROOTFS}/etc/pacman.d/" || die " Impossible to copy gnupg directory"
 	fi
 	
 	echo_display " Copying mirrorlist"
-	cp -af /etc/pacman.d/mirrorlist "${cont_rootfs}/etc/pacman.d/" || die " Impossible to copy mirrorlist list"
+	cp -af /etc/pacman.d/mirrorlist "${CONT_ROOTFS}/etc/pacman.d/" || die " Impossible to copy mirrorlist list"
 	
 	echo_display " Copying pacman database"
-	cp -f "/var/lib/pacman/sync/"*.* "${cont_rootfs}/var/lib/pacman/sync/" || die " Impossible to copy pacman database"
+	cp -f "/var/lib/pacman/sync/"*.* "${CONT_ROOTFS}/var/lib/pacman/sync/" || die " Impossible to copy pacman database"
 	
 	return 0 
 }
@@ -102,12 +126,12 @@ install_cont() {
 	pac_file
 	
 	# install package
-    pacman -r "${cont_rootfs}" -S $(grep -h -v ^# $target/$named/$workconf/pkglist_*) --noconfirm --config "${pac_conf}" --gpgdir "${gpg_dir}" || die " Impossible to install packages"
+    pacman -r "${CONT_ROOTFS}" -S $(grep -h -v ^# $TARGET/$named/$WORKCONF/pkglist_*) --noconfirm --config "${PAC_CONF}" --gpgdir "${GPG_DIR}" || die " Impossible to install packages"
 	
 	# pacman installation push mirrorlist to .pacsave,
 	# so copy again to erase the change
 	echo_display " Copying mirrorlist"
-	cp -af /etc/pacman.d/mirrorlist "${cont_rootfs}/etc/pacman.d/" || die " Impossible to copy mirrorlist list"
+	cp -af /etc/pacman.d/mirrorlist "${CONT_ROOTFS}/etc/pacman.d/" || die " Impossible to copy mirrorlist list"
 	
     return 0
 }
@@ -115,30 +139,30 @@ install_cont() {
 # customize container
 customize_cont() {
 	
-	mkdir -p "${cont_rootfs}""${src_functions}"
+	mkdir -p "${CONT_ROOTFS}""${SOURCES_FUNC}"
 			
 	echo_display " Copying customize"
-	cp -f "${target}/${named}/${workconf}/customize" "${cont_rootfs}""${src_functions}" || die " Impossible to copy file customizeCont" 
+	cp -f "${TARGET}/${named}/${WORKCONF}/customize" "${CONT_ROOTFS}""${SOURCES_FUNC}" || die " Impossible to copy file customizeCont" 
 	
 	echo_display " Copying build.conf"
-	cp -f "/etc/obarun/build.conf" "${cont_rootfs}""${src_functions}" || die " Impossible to copy build.conf"
+	cp -f "/etc/obarun/build.conf" "${CONT_ROOTFS}""${SOURCES_FUNC}" || die " Impossible to copy build.conf"
 	
 	echo_display " Copying create.conf"
-	cp -f "${target}/${named}/${workconf}/create.conf" "${cont_rootfs}""${src_functions}" || die " Impossible to copy cont_create.conf"
+	cp -f "${TARGET}/${named}/${WORKCONF}/create.conf" "${CONT_ROOTFS}""${SOURCES_FUNC}" || die " Impossible to copy cont_create.conf"
 	
-	echo_display " Copying locale file at ${cont_rootfs}/etc/"  
-    cp -fp /etc/locale.conf /etc/locale.gen "${cont_rootfs}/etc/" || die " Impossible to copy locale file"
+	echo_display " Copying locale file at ${CONT_ROOTFS}/etc/"  
+    cp -fp /etc/locale.conf /etc/locale.gen "${CONT_ROOTFS}/etc/" || die " Impossible to copy locale file"
 	
-	echo_display " Copy resolv.conf in ${cont_rootfs}"
-	cp -f /etc/resolv.conf "${cont_rootfs}/etc/resolv.conf" || die " Impossible to copy the file resolv.conf"
+	echo_display " Copy resolv.conf in ${CONT_ROOTFS}"
+	cp -f /etc/resolv.conf "${CONT_ROOTFS}/etc/resolv.conf" || die " Impossible to copy the file resolv.conf"
 	
-	echo_display " Copy pacman.conf in ${cont_rootfs}"
-	cp -f "${pac_conf}" "${cont_rootfs}"/etc || die " Impossible to copy the file ${pac_conf}"
+	echo_display " Copy pacman.conf in ${CONT_ROOTFS}"
+	cp -f "${PAC_CONF}" "${CONT_ROOTFS}"/etc || die " Impossible to copy the file ${PAC_CONF}"
 	
-	echo_display " Copy makepkg.conf in ${cont_rootfs}"
-	cp -f "${makepkg_conf}" "${cont_rootfs}"/etc || die " Impossible to copy the file ${makepkg_conf}"
+	echo_display " Copy makepkg.conf in ${CONT_ROOTFS}"
+	cp -f "${MAKEPKG_CONF}" "${CONT_ROOTFS}"/etc || die " Impossible to copy the file ${MAKEPKG_CONF}"
 	
-	chroot "${cont_rootfs}" "${src_functions}"/customize || die " Failed to enter on ${cont_rootfs} or Failed to execute the script customizeCont"
+	chroot "${CONT_ROOTFS}" "${SOURCES_FUNC}"/customize || die " Failed to enter on ${CONT_ROOTFS} or Failed to execute the script customizeCont"
 	
 	conf_console
 	
@@ -148,26 +172,26 @@ conf_console(){
 	
 	# enable getty on active ttys
 	# enable getty on active ttys
-    local nttys=$(cat "${lxc_conf}" | grep "^lxc.tty" | head -n1 | cut -d= -f2 | tr -d "[:blank:]")
-    local devttydir=$(cat "${lxc_conf}" | grep "^lxc.devttydir" | head -n1 | cut -d= -f2 | tr -d "[:blank:]")
+    local nttys=$(grep "^lxc.tty" "${START_CONF}"| head -n1 | cut -d= -f2 | tr -d "[:blank:]")
+    local devttydir=$(grep "^lxc.devttydir" "${START_CONF}" | head -n1 | cut -d= -f2 | tr -d "[:blank:]")
     local devtty=""
     
     # bind getty instances to /dev/<devttydir>/tty* if lxc.devttydir is set
     if [[ -n "${devttydir}" ]]; then
 		devtty="${devttydir}-"
-		echo "${devttydir}/console" >> "${cont_rootfs}/etc/securetty" || die " Impossible to set ${devttydir}/console in ${cont_rootfs}/etc/securetty"
+		echo "${devttydir}/console" >> "${CONT_ROOTFS}/etc/securetty" || die " Impossible to set ${devttydir}/console in ${CONT_ROOTFS}/etc/securetty"
 	fi
     
     # update securetty to allow console login if devttydir is set
     if [ -n "${devttydir}" ]; then
         for i in $(seq 1 ${nttys:-1}); do
-            echo "${devttydir}/tty${i}" >> "${cont_rootfs}/etc/securetty" || die " Impossible to set ${devttydir}/tty${i} in ${cont_rootfs}/etc/securetty"
+            echo "${devttydir}/tty${i}" >> "${CONT_ROOTFS}/etc/securetty" || die " Impossible to set ${devttydir}/tty${i} in ${CONT_ROOTFS}/etc/securetty"
         done
     fi
 	
 	# optional here, do not die if an error is created
-	echo "# For libvirt/Virtual Machine Monitor" >>${cont_rootfs}/etc/securetty
-    echo "pts/0"        >>${cont_rootfs}/etc/securetty
+	echo "# For libvirt/Virtual Machine Monitor" >> ${CONT_ROOTFS}/etc/securetty
+    echo "pts/0"        >> ${CONT_ROOTFS}/etc/securetty
     
     return 0
 }
@@ -175,25 +199,25 @@ conf_console(){
 # Write container configuration files
 cont_conf() {
 	
-    mkdir -p "${_cont_conf}" || die " Impossible to make directory ${_cont_conf}"
-    local config="${_cont_conf}/config" lxc_network_hwaddr=00:16:3e:$(openssl rand -hex 3| sed 's/\(..\)/\1:/g; s/.$//')
+    mkdir -p "${CONT_CONF}" || die " Impossible to make directory ${_cont_conf}"
+    local config="${CONT_CONF}/config" LXC_NETWORK_HWADDR=00:16:3e:$(openssl rand -hex 3| sed 's/\(..\)/\1:/g; s/.$//')
    
     rm -f ${config}
    
     echo "lxc.utsname = ${named}" >> "${config}" || die " Impossible to config lxc.utsname at ${config}"
-	echo "lxc.arch = ${arch}" >> "${config}" || die " Impossible to config lxc.arch at ${config}"
-	echo "lxc.rootfs = ${cont_rootfs}" >> "${config}" || die " Impossible to config lxc.rootfs at ${config}"
-    if [ -e "${lxc_conf}" ]; then 
-        echo "lxc.include = ${lxc_conf}" >> "${config}" || die " Impossible to config lxc.include at ${config}"
+	echo "lxc.arch = ${ARCH}" >> "${config}" || die " Impossible to config lxc.arch at ${config}"
+	echo "lxc.rootfs = ${CONT_ROOTFS}" >> "${config}" || die " Impossible to config lxc.rootfs at ${config}"
+    if [ -e "${START_CONF}" ]; then 
+        echo "lxc.include = ${START_CONF}" >> "${config}" || die " Impossible to config lxc.include at ${config}"
     fi
-    if (( ${create_bridge} ));then
-		echo "lxc.network.type = ${lxc_network_type}" >> "${config}" || die " Impossible to config lxc.network.type at ${config}"
-		echo "lxc.network.link = ${lxc_network_link}" >> "${config}" || die " Impossible to config lxc.network.link at ${config}"
-		echo "lxc.network.flags = ${lxc_network_flags}" >> "${config}" || die " Impossible to config lxc.network.flags at ${config}"
-		echo "lxc.network.ipv4 = ${lxc_network_ipv4}" >> "${config}" || die " Impossible to config lxc.network.ipv4 at ${config}"
-		echo "lxc.network.ipv4.gateway = ${lxc_network_ipv4_gateway}" >> "${config}" || die " Impossible to config lxc.network.ipv4.gateway at ${config}"
-		echo "lxc.network.name=${lxc_network_name}" >> "${config}" || die " Impossible to config lxc.network.name at ${config}"
-		echo "lxc.network.hwaddr=${lxc_network_hwaddr}" >> "${config}" || die " Impossible to config lxc.network.hwaddr at ${config}"
+    if (( ${CREATE_BRIDGE} ));then
+		echo "lxc.network.type = ${LXC_NETWORK_TYPE}" >> "${config}" || die " Impossible to config lxc.network.type at ${config}"
+		echo "lxc.network.link = ${LXC_NETWORK_LINK}" >> "${config}" || die " Impossible to config lxc.network.link at ${config}"
+		echo "lxc.network.flags = ${LXC_NETWORK_FLAGS}" >> "${config}" || die " Impossible to config lxc.network.flags at ${config}"
+		echo "lxc.network.ipv4 = ${LXC_NETWORK_IPV4}" >> "${config}" || die " Impossible to config lxc.network.ipv4 at ${config}"
+		echo "lxc.network.ipv4.gateway = ${LXC_NETWORK_IPV4_GATEWAY}" >> "${config}" || die " Impossible to config lxc.network.ipv4.gateway at ${config}"
+		echo "lxc.network.name=${LXC_NETWORK_NAME}" >> "${config}" || die " Impossible to config lxc.network.name at ${config}"
+		echo "lxc.network.hwaddr=${LXC_NETWORK_HWADDR}" >> "${config}" || die " Impossible to config lxc.network.hwaddr at ${config}"
     fi
     
 	return 0
@@ -202,13 +226,13 @@ cont_conf() {
 
 #(( EUID == 0 )) || die " ${bred}You must be run this script with root privileges"
 
-sanitize
+#sanitize
 
-if (( ${create_bridge} ));then
+if (( ${CREATE_BRIDGE} ));then
 	network_create
 fi
 
-mkdir -p "${cont_rootfs}"
+mkdir -p "${CONT_ROOTFS}"
 
 install_cont
 
@@ -216,5 +240,5 @@ customize_cont
 
 cont_conf
 
-echo_valid " The configuration file is stored in ${lxc_conf}."
+echo_valid " The configuration file is stored in ${START_CONF}."
 
diff --git a/templates/customize b/templates/customize
--- a/templates/customize
+++ b/templates/customize
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/bash
 #
 # This script is used by cont_create script for customize the fresh container 
 #
@@ -17,35 +17,31 @@
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 
 
-
-shopt -s extglob
-
 ##		Check is the functions file exits
+sourcing(){
+	
+	local list
+	
+	for list in /usr/lib/obarun/common_functions /tmp/obarun-build-tmp/{build.conf,create.conf} ; do
+		if [[ -f "${list}" ]]; then
+			source "${list}"
+		else
+			echo_error " Missing file : ${list}"
+			exit	
+		fi
+	done
+	
+	unset list
+}
+sourcing
 
-if [[ -f /usr/lib/obarun/common_functions ]]; then
-	source /usr/lib/obarun/common_functions
-else
-	echo "==>> Missing file : common_functions"
-	exit	
-fi
-
-if [[ -f /tmp/obarun-build-tmp/build.conf ]]; then
-	source /tmp/obarun-build-tmp/build.conf
-else
-	echo_error " Missing file : build.conf"
-	exit
-fi
-if [[ -f /tmp/obarun-build-tmp/create.conf ]]; then
-	source /tmp/obarun-build-tmp/create.conf
-else
-	echo_error " Missing file : create.conf"
-	exit
-fi
+shellopts_save
+shellopts_set_unset "extglob" 0
 
 custo_once() {
 	
 	local _tmp
-	_tmp="${src_functions}"
+	_tmp="${SOURCES_FUNC}"
 	
 	if [[ ! -d $_tmp ]]; then
 		mkdir -p -m0750 $_tmp || die " Impossible to create $_tmp"
@@ -60,16 +56,16 @@ custo_once() {
 
 config_hostname(){
 	
-	echo_display " Define hostname as : ${hostname}"
-	if [[ "$hostname" != "" ]]; then
+	echo_display " Define hostname as : ${HOSTNAME}"
+	if [[ -n "$HOSTNAME" ]]; then
 		sed -i 's/ .*$//' /etc/hosts || die " Impossible to define hosts"
 	fi
 
-	sed -i "s/HOSTNAME=.*$/HOSTNAME=$hostname/g" /etc/s6/s6.conf || die " Impossible to define hostname on s6.conf"
+	sed -i "s/HOSTNAME=.*$/HOSTNAME=$HOSTNAME/g" /etc/s6/s6.conf || die " Impossible to define hostname on s6.conf"
 	
-	echo "$hostname" > /etc/hostname || die " Impossible to define hostname"
-	sed -i '/127.0.0.1/s/$/ '$hostname'/' /etc/hosts || die " Impossible to define hosts"
-	sed -i '/::1/s/$/ '$hostname'/' /etc/hosts || die " Impossible to define hosts"
+	echo "$HOSTNAME" > /etc/hostname || die " Impossible to define hostname"
+	sed -i '/127.0.0.1/s/$/ '$HOSTNAME'/' /etc/hosts || die " Impossible to define hosts"
+	sed -i '/::1/s/$/ '$HOSTNAME'/' /etc/hosts || die " Impossible to define hosts"
 	
 	echo_valid " hostname was configured successfully"
 	
@@ -80,7 +76,7 @@ config_locale(){
 	
 	echo_display " Define locale"
 	locale-gen || die " Impossible to launch locale-gen"
-	echo LANG="$locale" > /etc/locale.conf || die " Impossible to define locale.conf"
+	echo LANG="$LOCALE" > /etc/locale.conf || die " Impossible to define locale.conf"
     echo LC_COLLATE=C >> /etc/locale.conf || die " Impossible to define locale.conf"
 	
 	echo_valid " Locale was created successfully"
@@ -91,13 +87,13 @@ custo_once config_locale
 config_localetime(){
 	
 	echo_display " Define localtime"
-	if [[ "$subzone" != "" ]]; then
-		ln -sf /usr/share/zoneinfo/$zone/$subzone /etc/localtime || die " Impossible to define localtime"
-		sed -i "s/TZ=.*$/TZ=$zone\/$subzone/g" /etc/s6/s6.conf || die " Impossible to define localtime on s6.conf"
+	if [[ "$SUBZONE" != "" ]]; then
+		ln -sf /usr/share/zoneinfo/$ZONE/$SUBZONE /etc/localtime || die " Impossible to define localtime"
+		sed -i "s/TZ=.*$/TZ=$ZONE\/$SUBZONE/g" /etc/s6/s6.conf || die " Impossible to define localtime on s6.conf"
 				
 	else
-		ln -sf /usr/share/zoneinfo/$zone /etc/localtime || die " Impossible to define localtime"
-		sed -i "s/TZ=.*$/TZ=$zone/g" /etc/s6/s6.conf || die " Impossible to define localtime on s6.conf"
+		ln -sf /usr/share/zoneinfo/$ZONE /etc/localtime || die " Impossible to define localtime"
+		sed -i "s/TZ=.*$/TZ=$ZONE/g" /etc/s6/s6.conf || die " Impossible to define localtime on s6.conf"
 	fi
 	
 	echo_valid " Localetime was configured successfully"
@@ -108,7 +104,7 @@ custo_once config_localetime
 config_keymap(){
 	
 	echo_display " Define keymap" 
-	sed -i "s,KEYMAP=.*$,KEYMAP=$keymap,g" /etc/s6/s6.conf || die " Impossible to set ${keymap} on s6.conf"
+	sed -i "s,KEYMAP=.*$,KEYMAP=$ZONE,g" /etc/s6/s6.conf || die " Impossible to set ${keymap} on s6.conf"
 		
 	echo_valid " Console keymap was configured successfully"
 	
@@ -117,13 +113,13 @@ custo_once config_keymap
 
 config_user(){
 	
-	echo_display " Define ${newuser}"
+	echo_display " Define ${NEWUSER}"
 	
-	user_add "${newuser}"
+	user_add "${NEWUSER}"
 	
-	echo "${newuser}:${passw_user}" | chpasswd || die " Failed to change $newuser password"
+	echo "${NEWUSER}:${PASSW_USER}" | chpasswd || die " Failed to change $newuser password"
 	
-	echo_valid " User ${newuser} was created successfully" 
+	echo_valid " User ${NEWUSER} was created successfully" 
 	
 }
 custo_once config_user
@@ -132,7 +128,7 @@ config_root(){
 	
 	echo_display " Define root"
 
-	echo "root:${passw_root}" | chpasswd || die " Failed to change root password"
+	echo "root:${PASSW_ROOT}" | chpasswd || die " Failed to change root password"
 	
 	echo_valid " root user was configured successfully" 
 	
@@ -141,12 +137,14 @@ custo_once config_root
 
 add_at_logroup(){
 	
-	echo_display " add {root,$newuser} at log group"
+	echo_display " add $NEWUSER at log group"
 	#gpasswd -a root log || die " Impossible to add root at log group"
-	gpasswd -a "$newuser" log || die " Impossible to add user ${newuser} at log group"
+	gpasswd -a "$NEWUSER" log || die " Impossible to add user ${newuser} at log group"
 	
 }
 custo_once add_at_logroup 
 
+shellopts_restore
+	
 echo_display " Customization terminate"
 
