improve functions lxc_command_parse, allow user option, add versionning on named variable

diff --git a/build_functions b/build_functions
--- a/build_functions
+++ b/build_functions
@@ -23,9 +23,8 @@ source /usr/lib/obarun/common_functions
 source /etc/obarun/build.conf
 
 templates="${templates:-/usr/share/obarun/obarun-build/templates}"
-workdir="build_pkg"
-workconf="build_conf"
-result_conf="/var/cache/obarun/pkgbuild/${named}"
+workdir="container"
+workconf="config"
 
 clean_install(){
 	echo_bold "clean install"
@@ -39,7 +38,7 @@ usage(){
 ${bold}Usage: ${0} [General options] [Sub options] name
 
 e.g obarun-build Create create container
-    obarun-build C c scontainer
+    obarun-build C c container
     obarun-build B b cups${reset}
     
 ${bold}General options :${reset}
@@ -58,19 +57,80 @@ ${bold}Sub options :${reset}
         but some parsing are impossible. The script will warm you.
         e.g obarun-build M info container
             obarun-build M i container
-        You can extra options from lxc
-        e.g obarun-build start container --logfile out
-        e.g obarun-build start container --help to show the help of 
-        the command lxc-start
+        You enter extra options from lxc
+           e.g obarun-build start container --logfile out
+           e.g obarun-build start container --help 
 EOF
 	exit 0
 }
-# {1} name of the container to create
-create(){
-	local file
-	local -a file_list
-	mapfile -t file_list < <(ls --group-directories-first ${templates}/*)
 
+# ${1} command to pass
+# ${2} arguments to pass. Can be empty
+lxc_command_parse(){
+	local command loop_ ret
+	local -a parse_opt rest_opt
+	
+	command="${1}"
+	parse_opt=( "${@}" )
+
+	
+	# check if lxc-${command} exist
+	for loop_ in $(ls /bin/|grep lxc-|sed 's:*::'); do
+		if [[ lxc-"${command}" == "${loop_}" ]]; then
+			ret=0
+			break
+		else
+			ret=1
+		fi
+	done
+	
+	if (( ! $ret )); then
+		if [[ "${command}" == @(ls|autostart|checkconfig|top|usernsexec) ]]; then
+			rest_opt=( "${parse_opt[@]:1}" )
+			"lxc-${command}" "${rest_opt[@]}" || die " Aborting command : lxc-${command} ${parse_opt[@]:1}"
+		else
+			if [[ -z "${parse_opt[1]}" ]]; then
+				die " name must not be empty"
+			fi
+			# if the container was not stopped before exiting of it
+			# the command stop may take time, just warm them
+			if [[ "${command}" == "stop" ]]; then
+					echo_notvalid " Trying to shutdown ${named}, this may take time..."
+			fi
+			rest_opt=( "${parse_opt[@]:2}" )
+			"lxc-${command}" -n "${parse_opt[1]}" "${rest_opt[@]}" || die " Aborting command : lxc-${command} -n ${parse_opt[1]} ${rest_opt[@]}"
+		fi
+	else
+		die " lxc-${command} doesn't exist"
+	fi
+	
+	#echo_valid " Done"
+	
+	return 0
+}
+
+# ${1} name of the container to create
+# ${@} arguments to pass. Can be empty
+create(){
+	local file named
+	local -a file_list _args
+	
+	mapfile -t file_list < <(ls --group-directories-first ${templates}/*)
+	
+	named="${1}"
+	_args=( "${@}" )
+	_args=( "${_args[@]:1}" )
+
+	# check if container directory exist
+	# if yes then exit container exit
+	check_dir "${target}/${named}"
+	if (( ! $? )); then
+		echo_info " Container already exit, do you want overwrite it? [y|n] :"
+		reply_answer
+		if (( $? )); then
+			die " Exiting"
+		fi
+	fi
 	# check if templates directory exist on $target
 	# create it if doesn't exist
 	check_dir "${target}/${named}/${workconf}"
@@ -89,11 +149,25 @@ create(){
 		fi
 	done
 	
-	cont_create "${named}"
+	# now we have to correct place to find configuration file to create and configure the container
+	# so, exporting the good one
+	export create_conf="${target}/${named}/${workconf}/create.conf"
+	export named="${named}"
+	export workdir="${workdir}"
+	export workconf="${workconf}"
+	lxc_command_parse "create" "${named}" -t "${target}/${named}/${workconf}/create" "${_args[@]}" || die " Impossible to create the container"
+	
 }
 
+# ${1} name of the container
+# ${@} arguments to pass. Can be empty
 build(){
-	
+	local named
+	local -a _args
+	named="${1}"
+	_args=( "${@}" )
+	_args=( "${_args[@]:1}" )
+
 	# check if sources variables is set
 	if [[ -z "${sources}" ]]; then
 		die " Aborting : sources variables on /etc/obarun/build.conf is not set"
@@ -110,89 +184,49 @@ build(){
 	if (( $? )); then
 		die " Aborting : a PKGBUILD file must at least exist into ${sources} directory"
 	fi
+	# retrieve pkgver and pkgrel to implemente them onto the name
+	pkgver_=$(grep pkgver= "${sources}/${named}/PKGBUILD" | awk -F"=" '{print $2}')
+	pkgrel_=$(grep pkgrel= "${sources}/${named}/PKGBUILD" | awk -F"=" '{print $2}')
+	named_version="${pkgver_}-${pkgrel_}"
 	
 	# be sure that the named container doesn't exist
-	lxc-ls | grep "${1}" &>/dev/null
+	lxc-ls | grep "${named}-${named_version}" &>/dev/null
 	if (( ! $? )); then
 		echo_error " Container already exist, please choose another name"
 	fi
 	
 	# create the container
-	create "${named}"
+	create "${named}-${named_version}" "${_args[@]}"
 	
 	# copy $sources/$named files onto the container
-	mkdir -p "${target}/${named}/${workdir}/rootfs/tmp/${named}" || die " Impossible to create ${target}/${named}/${workdir}/rootfs/tmp/${named}"
-	cp -r "${sources}/${named}" "${target}/${named}/${workdir}/rootfs/tmp/" || die " Impossible to copy file from ${sources}/${named}"
-	
+	#mkdir -p "${target}/${named}-${named_version}/${workdir}/rootfs/tmp/${named}-${named_version}" || die " Impossible to create ${target}/${named}/${workdir}/rootfs/tmp/${named}-${named_version}"
+	cp -ra "${sources}/${named}" "${target}/${named}-${named_version}/${workdir}/rootfs/tmp/${named}-${named_version}" || die " Impossible to copy file from ${sources}/${named}-${named_version}"
+	#mv "${target}/${named}-${named_version}/${workdir}/rootfs/tmp/${named}" "${target}/${named}-${named_version}/${workdir}/rootfs/tmp/${named}-${named_version}"
+	#exit
 	# remove existing package and src, pkg directories
-	rm -f "${target}/${named}/${workdir}/rootfs/tmp/${named}"/*.pkg.* &>/dev/null
-	rm -rf "${target}/${named}/${workdir}/rootfs/tmp/${named}"/{src,pkg} &>/dev/null
+	rm -f "${target}/${named}-${named_version}/${workdir}/rootfs/tmp/${named}"/*.pkg.* &>/dev/null
+	rm -rf "${target}/${named}-${named_version}/${workdir}/rootfs/tmp/${named}"/{src,pkg} &>/dev/null
 	
 	# start the container
-	lxc-start -n "${named}" || die " Aborting : impossible to start the container"
+	lxc_command_parse "start" "${named}-${named_version}" || die " Aborting : impossible to start the container ${named}-${named_version}"
 	
 	# give a good permissions at the tmp/$named onto the container
-	lxc-attach -n "${named}" --clear-env -v named="${named}" -v newuser="${newuser}" -- bash -c 'echo "${newuser} ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers'
-	lxc-attach -n "${named}" --clear-env -v named="${named}" -v newuser="${newuser}" -- bash -c 'chown -R ${newuser}:users /tmp/${named}'
+	lxc_command_parse "attach" "${named}-${named_version}" --clear-env -v named="${named}-${named_version}" -v newuser="${newuser}" -- bash -c 'echo "${newuser}" "ALL=(ALL)" NOPASSWD: ALL >> /etc/sudoers'
+	lxc_command_parse "attach" "${named}-${named_version}" --clear-env -v named="${named}-${named_version}" -v newuser="${newuser}" -- bash -c 'chown -R "${newuser}":users /tmp/"${named}"'
 	
 	# build the package
-	lxc-attach -n "${named}" --clear-env -v named="${named}" -v newuser="${newuser}" -- bash -c 'cd /tmp/${named}; su ${newuser}  -c "updpkgsums; makepkg -Cs --noconfirm"' 
+	lxc_command_parse "attach" "${named}-${named_version}" --clear-env -v named="${named}-${named_version}" -v newuser="${newuser}" -- bash -c 'cd /tmp/"${named}"; su "${newuser}"  -c "updpkgsums; makepkg -Cs --noconfirm"'
 	
 	# copy the resulting package on the right place
-	check_dir "${result_pkg}"
+	check_dir "${result_pkg}/${named}/${named_version}"
 	if (( $? )); then
-		mkdir -p "${result_pkg}"
+		mkdir -p "${result_pkg}/${named}/${named_version}"
 	fi
-	cp -f "${target}/${named}/${workdir}/rootfs/tmp/${named}"/*.pkg.tar.* "${result_pkg}" || echo_info " WARNING : the resulting package can be copied to ${result_pkg}/${named}"
+	cp -f "${target}/${named}-${named_version}/${workdir}/rootfs/tmp/${named}-${named_version}"/*.pkg.tar.* "${result_pkg}/${named}/${named_version}" || echo_info " WARNING : the resulting package can be copied to ${result_pkg}/${named}/${named_version}"
 	
 	# stop the container
-	lxc-stop -n "${named}" -k
-}
+	lxc_command_parse "stop" "${named}-${named_version}" -k
 
-# ${1} regex for lxc- command
-# ${2} name of the container to control
-
-lxc_command_parse(){
-	local command named loop_ opt ret
-	command="${1}"
-	named="${2}"
-	
-	if [[ ! -z "${3}" ]]; then
-		opt="${3}"
-	fi
-	
-	if [[ -z "${named}" ]] && [[ "${command}" != @(ls|autostart|checkconfig|top|usernsexec) ]]; then
-		die " name must not be empty"
-	fi
-	for loop_ in $(ls /bin/|grep lxc-|sed 's:*::'); do
-		if [[ lxc-"${command}" == "${loop_}" ]]; then
-			ret=0
-			break
-		else
-			ret=1
-		fi
-	done
-				
-	if (( ! $ret )); then
-		
-		case "${command}" in
-			ls|autostart|checkconfig|top|usernsexec)
-				#echo eval=eval lxc-${command} named=${named}
-				eval lxc-"${command}" '${named}' ## replacement of $opt by $named here
-				;;
-			*)	
-				if [[ "${command}" == "stop" ]]; then
-					echo_notvalid " Trying to shutdown ${named}"
-				fi
-				#echo eval=eval lxc-${command} -n named=${named} opt=${opt}
-				eval lxc-"${command}" -n "${named}" "${opt}"
-				;;
-		esac
-	else
-		die " lxc-${command} doesn't exist"
-	fi
-	
-	exit 0
 }
 
 remake(){
@@ -206,9 +240,11 @@ remake(){
 ################################################################################################################
 # ${1} name of the container to create
 cont_create(){
-		export named="${1}"
-		export workdir="${workdir}"
-		export workconf="${workconf}"
-		export cont_create_conf="${target}/${named}/${workconf}/cont_create.conf"
-		lxc-create -n "${named}" -t "${target}/${named}/${workconf}/cont_create" || die " Impossible to create the container"
+	named="${1}"
+	export pass_named="${named}"
+	export workdir="${workdir}" 
+	export workconf="${workconf}" 
+	export cont_create_conf="${target}/${named}/${workconf}/cont_create.conf" 
+	lxc_command_parse "create" "${named}" -t "${target}/${named}/${workconf}/cont_create" || die " Impossible to create the container"
+
 }
